services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'task_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: YES
    volumes:
      - ./taskmanagerservice/db-init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
  task-manager:
    build:
      dockerfile: taskmanagerservice/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  to-do-frontend:
    build:
      dockerfile: front/Dockerfile
    container_name: to-do-frontend
    ports:
      - "3000:80"
