apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /$1
  #  nginx.ingress.kubernetes.io/enable-cors: "true"
  #  nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
  #  nginx.ingress.kubernetes.io/cors-allow-origin: "https://todoapp.info"
  #  nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
    - host: todoapp.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /api/tasks
            pathType: Prefix
            backend:
              service:
                name: taskmanagerservice-service
                port:
                  number: 8081
          - path: /api/files
            pathType: Prefix
            backend:
              service:
                name: filestorageservice-service
                port:
                  number: 8082
