services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: 'task-db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db-init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
  task-manager:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql