apiVersion: v1
kind: Service
metadata:
  name: taskmanagerservice-service
spec:
  selector:
    app: taskmanagerservice-mysql
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
