apiVersion: v1
kind: Service
metadata:
  name: filestorageservice-service
spec:
  selector:
    app: filestorageservice-mysql
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
